```{=html}
<!-- Note: Section files must have no YAML header and only Report.qmd should have one. 
# If you have trouble compiling, try Create with File → New File → Text File (not Quarto Document, which inserts a header)
# Save with a .qmd file -->
```

# **Introduction**

The Palmer penguins data set consists of three main species (Adelie, Chinstrap, Gentoo) that reside on 3 main islands (Torgensen,Dream, Biscoe) in the Antartic. This data has been collected by researchers at the Palmer station in Antartica between the years of 2007-2009, this is a United States research station that's situated at the Anvers Island in Antartica. The data contains a mix of categorical (sex, Island and species) and numerical data (Bill length, Flipper length, Body mass etc) (Palmer Station Antarctica LTER & Gorman, 2020), making this data set helpful for statistical analysis as you can pull inferences out of the categorical data using the numerical data such as comparing bill length among species or body mass among sexes. For this data set, there are a limited number of sources, however the sources present show that the palmer data set has shown that this data set has proven very useful when teaching and demonstrating statistical analysis and visualizing data in R, the purpose of this source was to show how this data can be used for various types of data exoploration and anlysis, the authors used the data to make several inferences on all the variables to prove this such as what is being done in this report (Horst e al., 2022). Research has also been done that is similar to the inference we are making in this report such as measuring body characteristics between same species and using those inferences to determine how males and females obtain food, models from this source correctly classified approximately 90 percent of individuals from this data set with several infeernces made about sex between species (Gorman et al., 2014). These sources show that this data set is especially good for this research question as the issue has been tackled before.

The males and females of a similar species often vary in size, males are usually bigger. This would mean that a big male of a very small species could be similar in size to a small female of a bigger species. If we attempt to separate these species by just looking at the sizes of the species and ignore the sexes of the penguins, some penguins might end up getting misclassified. This question aims to check if that actually occurs in the data, and whether this inclusion of sexes in the analysis would help reduce those misclassifications.
